### ISSUE TITLE
étudier le protocol ouvert oEmbed

### ISSUE THREAD

**Issue by amnesic** [LiberTIC/ODEV2#3]
Intéressant pour insérer plusieurs types : photo, vidéo, URL ou extrait HTML , d’une page web dans une autre page. (avec accès au metadata : licence , auteur ...etc...)

http://www.oembed.com

**Comment by sim51** [comment]
Vaut mieux de l'opengraph : http://ogp.me/ c'est plus utilisé

**Comment by ronanguilloux** [comment]
Ca se discute ! parce qu'il y a aussi ça : https://schema.org/CreativeWork

Il peut être assez intéressant de trouver les dénominateurs communs à ces différentes modélisations d'une "ressource" tierce.

**Comment by sim51** [comment]
Les microdata permettent de faire du web semantique et de mieux se faire indexer par les moteurs de recherche.

L'opengraph, lui ne sert qu'au partage d'une page sur un réseau social comme facebook, twitter, ou G+. Cela permet d'avoir un titre, une description, et une image qui s'affiche correctement dans twiter (par exemple) lorsqu'on y met une url.

Pour moi les deux sont complémentaires et sont à implémenter (en tout cas c'est ce que je fais sur mes sites ^^)

**Comment by Errorname** [comment]
Le protocole oEmbed a été implémenté avec le commit: bc118da571bbfd99ec0adf13b0e065833501164b
