### ISSUE TITLE
ERREUR: la relation « public.calendarobject » n'existe pas

### ISSUE THREAD

**Issue by Djyp** [LiberTIC/ODEV2#37]
Bonjour,

J'ai donc installé ODE sans trop de mal mis à part tout ce qui touche à postgres (9.1). J'ai jamais vraiment de mal avec postgres mais là je rage un peu. J'arrive à faire fonctionner ODE mais je ne peux pas cliquer sur Calendar car j'ai l'erreur "ERREUR: la relation « public.calendarobject » n'existe pas"
Bon j'aurais dû m'en douter puisquie make pgInit produit des erreurs... y'a toujours des histoires de contraintes qui marchent pas...
Pourquoi moi ça foire ? C'est une question de version de Pg ? Faut que je lance ode.sql avec des droits particuliers ?

**Comment by Djyp** [comment]
psql:./doc/postgresql/ode.sql:10: ERREUR:  paramètre de configuration « lock_timeout » non reconnu
SET
SET
SET
SET
ALTER DATABASE
Connexion SSL (chiffrement : DHE-RSA-AES256-SHA, bits : 256)
Vous êtes maintenant connecté à la base de données « ode » en tant qu'utilisateur « postgres ».
SET
psql:./doc/postgresql/ode.sql:30: ERREUR:  paramètre de configuration « lock_timeout » non reconnu
SET
SET
SET
SET
psql:./doc/postgresql/ode.sql:41: ERREUR:  erreur de syntaxe sur ou près de « NOT »
LIGNE 1 : CREATE SCHEMA IF NOT EXISTS public;
                           ^
ALTER SCHEMA
COMMENT
CREATE EXTENSION
COMMENT
SET
SET
SET
psql:./doc/postgresql/ode.sql:96: ERREUR:  la relation « calendar » existe déjà
ALTER TABLE
psql:./doc/postgresql/ode.sql:112: ERREUR:  la relation « calendarchange » existe déjà
ALTER TABLE
psql:./doc/postgresql/ode.sql:127: ERREUR:  la relation « calendarchanges_id_seq » existe déjà
ALTER TABLE
ALTER SEQUENCE
psql:./doc/postgresql/ode.sql:157: ERREUR:  le type « json » n'existe pas
LIGNE 8 :     extracted_data json,
                             ^
psql:./doc/postgresql/ode.sql:160: ERREUR:  la relation « calendarobject » n'existe pas
psql:./doc/postgresql/ode.sql:172: ERREUR:  la relation « calendars_uid_seq » existe déjà
ALTER TABLE
ALTER SEQUENCE
psql:./doc/postgresql/ode.sql:197: ERREUR:  la relation « principal » existe déjà
ALTER TABLE
psql:./doc/postgresql/ode.sql:212: ERREUR:  la relation « principal_id_seq » existe déjà
ALTER TABLE
ALTER SEQUENCE
psql:./doc/postgresql/ode.sql:250: ERREUR:  la relation « users » existe déjà
ALTER TABLE
psql:./doc/postgresql/ode.sql:265: ERREUR:  la relation « user_uid_seq » existe déjà
ALTER TABLE
ALTER SEQUENCE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
psql:./doc/postgresql/ode.sql:319: ERREUR:  la valeur d'une clé dupliquée rompt la contrainte unique « calendar_pkey »
DÉTAIL : La clé « (uid)=(1) » existe déjà.
CONTEXTE : COPY calendar, ligne 1 : « 1    principals/admin    Calendrier Test 6404AFAC-6578-4A8B-B8E5-1C916BEB8113    1   Calendrier de test  \N  \N  ... »

##  setval 

```
  0
```

(1 ligne)

psql:./doc/postgresql/ode.sql:347: ERREUR:  la relation « calendarobject » n'existe pas
psql:./doc/postgresql/ode.sql:348: commande . invalide

##  setval 

```
  1
```

(1 ligne)

##  setval 

```
  3
```

(1 ligne)

##  setval 

```
  1
```

(1 ligne)

psql:./doc/postgresql/ode.sql:399: ERREUR:  la valeur d'une clé dupliquée rompt la contrainte unique « user_pkey »
DÉTAIL : La clé « (id)=(1) » existe déjà.
CONTEXTE : COPY users, ligne 1 : « 1   admin   admin   admin@admin.fr  admin@admin.fr  buk14ljud3scw4k80k8kcckks8gc8o0 mnvGN+JXg8jkCr+9AZg7fCP8... »
psql:./doc/postgresql/ode.sql:408: ERREUR:  les clés primaires multiples ne sont pas autorisées pour la table « calendar »
psql:./doc/postgresql/ode.sql:417: ERREUR:  les clés primaires multiples ne sont pas autorisées pour la table « calendarchange »
psql:./doc/postgresql/ode.sql:426: ERREUR:  la relation « calendarobject » n'existe pas
psql:./doc/postgresql/ode.sql:435: ERREUR:  les clés primaires multiples ne sont pas autorisées pour la table « users »
psql:./doc/postgresql/ode.sql:443: ERREUR:  la relation « fki_cal_fkey » existe déjà
psql:./doc/postgresql/ode.sql:451: ERREUR:  la relation « calendarobject » n'existe pas
psql:./doc/postgresql/ode.sql:460: ERREUR:  la contrainte « cal_fkey » de la relation « calendarchange » existe déjà
psql:./doc/postgresql/ode.sql:469: ERREUR:  la relation « calendarobject » n'existe pas
REVOKE
REVOKE
GRANT
GRANT
done

**Comment by Djyp** [comment]
Trouvé !!!

Le type json est arrivé dans Postgres à partir de la version 9.2. Ayant le version 9.1 sous Wheezy j'étais un peu bloqué... 
Avec l'aide de http://nixmash.com/postgresql/upgrading-postgresql-9-1-to-9-3-in-ubuntu/ j'ai installé la version 9.3 (pourquoi s'en tenir à la 9.2) et ça fonctionne !

Je vous propose de modifier votre README.md pour changer Postgresql 9.x. en Postgresql 9.2 !

**Comment by ronanguilloux** [comment]
Hello @Djyp, suite à ton retour, le README.md a été augmenté avec la précision sur la version de Postgre. Merci pour le feedback.
